#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd & tradingview & zoom & picom &

bspc monitor DVI-D-0 -d 1 2 3 4
bspc monitor VGA-1-1 -d 5 6 7

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Telegram desktop=^2
bspc rule -a zoom desktop=^3
bspc rule -a TradingView desktop=^1
